services:
  db-service-customers:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - customers-network

  app:
    build: .
    container_name: api-customers
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db-service-customers
    networks:
      - customers-network
      - microservices_network

volumes:
  db_data:

networks:
  customers-network:
    driver: bridge
  microservices_network:
    external: true